#!/bin/sh

# Jenkins Swarm Client integration for NUT CI farm
# Copyright (C)
#   2021-2026 by Jim Klimov <jimklimov+nut@gmail.com>
# License: MIT

# Stopper for Jenkins swarm agent (can do with shared homedir)
#   to wait gracefully or `kill` their processes ungracefully
#   (aborting any running job parts).
# Separate script so different OS integrations can use it commonly.
# NOTE: To start the agents, see swarm-client-nutci.sh and various
#  OS-specific method scripts that call it.
# Expected structure:
#   SCRIPTDIR/swarm-client-nutci.sh
#   SCRIPTDIR/jenkins-agent-toggle.sh
#   SCRIPTDIR/swarm-client-X.YZ.jar
#   SCRIPTDIR/jenkins-swarm-nutci.yml.in
#   SCRIPTDIR/jenkins-swarm-nutci.token (github token generated for the nut-swarm account)
#
# Per worker:
#   SCRIPTDIR/../jenkins-`hostname`/
#   SCRIPTDIR/../jenkins-`hostname`/jenkins-swarm.yml (generated by start script, references token etc.)

SCRIPTDIR="`dirname \"$0\"`"
SCRIPTDIR="`cd \"${SCRIPTDIR}\" && pwd`"

# NOTE: At this point we may not know the AGENT_NAME from a config file
# but may have it from service unit configuration etc. Normally we get
# (or reset) it with jenkins-swarm-prestart.include-early file.
_AGENT_NAME="${AGENT_NAME-}"
_AGENT_DIR="${AGENT_DIR-}"
[ -n "${_AGENT_NAME-}" ] || _AGENT_NAME="`hostname | sed 's,\..*$,,'`"
[ -n "${_AGENT_DIR-}" ] ||  _AGENT_DIR="${SCRIPTDIR}/../jenkins-${_AGENT_NAME}/"

# Jenkins agent run-time user
[ -n "${JRT_USER-}" ] || {
    [ -n "${daemon_user}" ] && JRT_USER="${daemon_user}" || JRT_USER="abuild"
}

stop_graceful() {
    if [ -d "${_AGENT_DIR}" ] ; then
        echo "`date -u`: Running graceful shutdown (note it can take ages if the agent is busy)..." >&2
        ( cd "${_AGENT_DIR}"/ && "${SCRIPTDIR}/jenkins-agent-toggle.sh" stop-graceful )
        echo "`date -u`: Graceful shutdown completed" >&2
    else
        # Did the caller specify a name? Toggler can use that...
        if [ -n "${AGENT_NAME-}" ] ; then
            echo "`date -u`: Running graceful shutdown (note it can take ages if the agent is busy)..." >&2
            ( cd "${SCRIPTDIR}" && ./jenkins-agent-toggle.sh stop-graceful )
            echo "`date -u`: Graceful shutdown completed" >&2
        else
            echo "`date -u`: Graceful shutdown skipped: AGENT_NAME/AGENT_DIR not known and guesses failed" >&2
        fi
    fi
}

list_agent_pids() {
    (ps -ef || ps -xawwu) 2>/dev/null | grep java | grep swarm-client | grep -v grep | grep -w "${JRT_USER}" | awk '{print $2}'
}

kill_agent() {
    echo "`date`: Stopping swarm-agent" >&2
    kill -15 `list_agent_pids`
    echo "`date`: Waiting for swarm-agent PIDs to disappear" >&2
    while sleep 1 ; do
        if [ x"`list_agent_pids`" = x ] ; then
            break
        fi
    done
    echo "`date`: Stopped swarm-agent" >&2
}

case "$1" in
    -h|-help|help)
        cat << EOF
$0 {-h|-help|help}	This message
$0 stop	Graceful stop and wait for jobs to finish, then kill the agent JAR
$0 kill	Kill the agent JAR immediately
$0 list	List the agent PIDs
EOF
        ;;

    stop)
        stop_graceful
        kill_agent
        ;;

    kill)
        echo "`date`: WARNING: Ungraceful stop!" >&2
        kill_agent
        ;;

    check|list) list_agent_pids ;;

    stop_graceful|list_agent_pids|kill_agent) "$1" ;;

    start)
        echo "ERROR: Script '$0' is only responsible for stopping. See OS-dependent integration to start." >&2
        exit 1
        ;;

    *)  echo "ERROR: Script '$0' does not support arg(s): $*" >&2
        exit 1
        ;;
esac
